### ISSUE TITLE
Run program on system startup

### ISSUE THREAD

**Issue by TAWinterton2** [andrewsng/assistive-technology#43]
Saving and Printing (opening the file on startup) -- see notes from `Draft Usability Testing Script & Checklist`.

**Comment by TechSolomon** [comment]
Further reading: https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd & https://techcommunity.microsoft.com/t5/windows-11/how-to-disable-startup-programs-in-windows-11-3-ways/m-p/3249863
